# This file contains values from Cookiecutter

default_context:
  project_name: "qsipost"
  project_description: "Post-processing for QSIPrep's outputs"
  organization: "qsipost"
  license: "MIT"
  minimal_python_version: 3.9
  github_name: "GalKepler"
  email: "galkepler@gmail.com"
  version: "0.1.0"
  line_length: "88"
  create_example_template: "cli"
