BASE_WORKFLOW_DESCRIPTION = """
Results included in this manuscript come from preprocessing
performed using *KePost* {kepost_ver}
which is based on *Nipype* {nipype_ver}
(@nipype1; @nipype2; RRID:SCR_002502).
"""

BASE_POSTDESC = """
Many internal operations of *KePost* use
*Nilearn* {nilearn_ver} [@nilearn, RRID:SCR_001362], *MRtrix* {mrtrix_ver} [@mrtrix3, SCR_006971] and *dipy* {dipy_ver} [@dipy].
For more details of the pipeline, see [the section corresponding
to workflows in *KePost*'s documentation]\
(https://kepost.readthedocs.io/en/latest/workflows.html \
"KePost's documentation").


### Copyright Waiver

The above boilerplate text was automatically generated by KePrep
with the express intention that users should copy and paste this
text into their manuscripts *unchanged*.
It is released under the [CC0]\
(https://creativecommons.org/publicdomain/zero/1.0/) license.

### References

"""
