DIFFUSION_WF_OUTPUT_ENTITIES = dict(
    wholebrain_parcellation={
        "space": "dwi",
        "desc": "",
        "direction": "",
        "label": "WholeBrain",
        "suffix": "dseg",
        "extension": ".nii.gz",
    },
    gm_cropped_parcellation={
        "space": "dwi",
        "desc": "",
        "direction": "",
        "label": "GM",
        "suffix": "dseg",
        "extension": ".nii.gz",
    },
    t1w_in_dwi_space={
        "space": "dwi",
        "desc": "",
        "direction": "",
        "datatype": "anat",
        "suffix": "T1w",
        "extension": ".nii.gz",
    },
    dti_derived_parameters={
        "acquisition": "dt",
        "res": "dwi",
        "suffix": "dwiref",
        "extension": ".nii.gz",
    },
    tissue_dwiref_probseg={
        "res": "dwi",
        "space": "dwi",
        "desc": "",
        "direction": "",
        "suffix": "probseg",
        "extension": ".nii.gz",
    },
    brain_mask={
        "space": "dwi",
        "desc": "brain",
        "direction": "",
        "suffix": "mask",
        "extension": ".nii.gz",
        "datatype": "anat",
    },
    snr_image={
        "space": "dwi",
        "desc": "snr",
        "direction": "",
        "suffix": "dwiref",
        "extension": ".nii.gz",
        "reconstruction_software": "qc",
    },
    snr_csv={
        "space": "dwi",
        "desc": "snr",
        "direction": "",
        "suffix": "qc",
        "extension": ".csv",
        "reconstruction_software": "qc",
    },
    eddy_qc={
        "space": "dwi",
        "desc": "eddy",
        "direction": "",
        "suffix": "qc",
        "extension": ".json",
        "reconstruction_software": "qc",
    },
    parcellations={
        "space": "dwi",
        "subtype": "parcellations",
        "suffix": "parc",
        "extension": ".pkl",
    },
)
